---
# update_packages/tasks/dnf.yml

- name: Update all packages to the latest version
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  become: true
  become_method: ansible.builtin.sudo

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: true
  become: true
  become_method: ansible.builtin.sudo

# https://serverfault.com/questions/671863/need-to-check-whether-you-need-to-reboot-for-a-kernel-update
- name: Register if a reboot is required
  ansible.builtin.shell: |
    if ! (dnf needs-restarting -r | grep -q 'Reboot should not be necessary.' >/dev/null); then echo "true"; fi
  args:
    executable: /bin/bash
  register: reboot_required
  ignore_errors: true

- name: "Set reboot condition"
  ansible.builtin.set_fact:
    reboot_condition: true
  when: reboot_required.stdout == 'true'
