---
# tasks file for update_packages
# update_packages/tasks/main.yml

- name: Update Packages (apt)
  include_tasks: apt.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Update Packages (dnf)
  include_tasks: dnf.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Update Packages (snap)
  include_tasks: snap.yml
  when: ansible_facts['system'] == "Linux"

- name: Reboot after updates
  include_tasks: reboot.yml
  when: reboot_after_updates is true

- name: Shutdown after updates
  include_tasks: shutdown.yml
  when: shutdown_after_updates is true
