---
# update_packages/tasks/shutdown.yml

- name: "Shutdown after updating ({{ ansible_distribution }})"
  community.general.shutdown:
  ignore_errors: true
  become: true
  become_method: ansible.builtin.sudo
  when: (ansible_system == "Linux") and
        (shutdown_after_updates is true)

# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_command_module.html#examples

- name: "Shutdown after updating ({{ ansible_facts['os_family'] == Windows }})"
  ansible.windows.win_command:
    cmd: shutdown.exe /t 0
  ignore_errors: true
  become: true
  become_method: ansible.builtin.runas
  when: (ansible_facts['os_family'] == "Windows") and
        (shutdown_after_updates is true)
