---
# update_pacakges/tasks/snap.yml

- name: Update package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Refresh all snaps
  ansible.builtin.shell: |
    snap refresh
  args:
    executable: /bin/bash
  when: "'snapd' in ansible_facts.packages"
  become: true
  become_method: ansible.builtin.sudo
