---
# molecule/default/converge.yml
# SPDX-License-Identifier: MIT
#
# The converge.yml file is the Ansible playbook Molecule uses to run roles and collections
# across the containers / VM's it builds. Anything you'd normally configure for roles in
# the playbook.yml file can be set here.

- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    # This block was taken directly from: https://github.com/geerlingguy/ansible-role-docker/blob/master/molecule/default/converge.yml#L6
    - name: Wait for systemd to complete initialization  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 5
      delay: 2
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1
  tasks:
    - name: Enumerate Ansible Facts
      ansible.builtin.debug:
        # msg: "This is the effective test"
        var: ansible_facts['system']
  roles:
    - role: straysheep_dev.update_packages
